### ISSUE TITLE
failed to sign domain, challenge doesn't seem to be written

### ISSUE THREAD

**Issue by waspinator** [SteveLTN/https-portal#92]
docker compose file

```
version: '2'

services:

  https-portal:
    image: steveltn/https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'sub.domain.notcom -> http://wordpress'
      STAGE: "production" # options: local, staging, production
      # FORCE_RENEW: "true"

  wordpress:
    image: wordpress
```

output:

```
https-portal_1  | Verifying sub.domain.notcom...
https-portal_1  | Traceback (most recent call last):
https-portal_1  |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1  |     main(sys.argv[1:])
https-portal_1  |   File "/bin/acme_tiny", line 194, in main
https-portal_1  |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1  |   File "/bin/acme_tiny", line 123, in get_crt
https-portal_1  |     wellknown_path, wellknown_url))
https-portal_1  | ValueError: Wrote file to /var/www/default/challenges/6DUzSI8sK_p6kqKBKgq3I5qiteD6H9X54ljqIvzEV8s, but couldn't download http://sub.domain.notcom/.well-known/acme-challenge/6DUzSI8sK_p6kqKBKgq3I5qiteD6H9X54ljqIvzEV8s
https-portal_1  | ================================================================================
https-portal_1  | Failed to sign sub.domain.notcom, is DNS set up properly?
https-portal_1  | ================================================================================
https-portal_1  | Failed to obtain certs for sub.domain.notcom
```

It doesn't seem like the challenge is being written, since I get an nginx 404 when trying to access the url. I also can't see anything in the `/var/www/default/challenges/6DUzSI8sK_...` file when `ls -la`.

```
root@21a9f5e725ec:/var/www/default/challenges# ls -la
total 0
drwxr-xr-x. 1 root root  6 Apr 11 02:19 .
drwxr-xr-x. 1 root root 24 Mar 29 21:21 ..
-rw-r--r--. 1 root root  0 Mar 29 21:21 .gitkeep
```

I don't think it's an issue with DNS, as I can access the site using the domain name when just running `docker run --rm -p 80:80 nginx`

If I place a file in `/var/www/default/challenges` I can `curl http://sub.domain.notcom/.well-known/acme-challenge/poop.html` and get a response.

**Comment by SteveLTN** [comment]
I believe after a failure to access the challenge file, ACME-tiny will actually remove it. 

In the verification, Let's Encrypt server will try to access your computer, not from your localhost. Is it possible that the DNS record is not propagated from them? How long is it since you set up DNS records? Or is it possible that 80/443 is blocked for some client address?

**Comment by waspinator** [comment]
Thanks for working on this system. It makes lets encrypt painless, and I have used it several time successfully, even on the same domain, just another sub-domain.

I can access the URL from a few places outside of my local lan using the link that's shown in the console output. It just shows a nginx 404 page though. That makes sens if ACME-tiny deletes the file, but it also shows that DNS and port 80 should be working. I registered it with my DNS 10+ days ago so it should have propagated. Trying to access it at `https://` times out, but I think that's how it's supposed to work until it actually gets a certificate. 

I tried a simpler docker-compose file to test. Is there something else I can try to troubleshoot why this isn't working?

Thanks again

	https-portal:
	  image: steveltn/https-portal:1
	  ports:
	    - '80:80'
	    - '443:443'
	  environment:
	    DOMAINS: 'sub.domain.notcom'
	    # STAGE: 'production'

   And the URL that gives the 404 nginx error:

 `http://sub.domain.notcom/.well-known/acme-challenge/tu7rHAo8xFvf0H0XpT4UIzrtmXrfU3XxBd3AyiLfN_o`

**Comment by waspinator** [comment]
I gave up on centos and switch back to ubuntu. works as expected.

**Comment by wdmtech** [comment]
I'm having this same issue on Ubuntu (ubuntu:amd64-xenial)

DNS is set up and `curl my-domain.co.uk` returns my index.html expected.

docker-compose.yml (application)

```
version: '2'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - '80:80'
      - '443:443'
    environment:
      # tell HTTPS-PORTAL to set up the domain
      VIRTUAL_HOST: my-domain.co.uk
```

And my`https-portal` docker-compose.yml

```
version: '2'
services:
  https-portal:
    restart: always
    image: steveltn/https-portal:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Here's the `https-portal` container log

```
2017/07/16 19:14:31 [reconfig]: Signing certificates from https://acme-staging.api.letsencrypt.org ...
2017/07/16 19:14:31 [reconfig]: Parsing account key...
2017/07/16 19:14:31 [reconfig]: Parsing CSR...
2017/07/16 19:14:31 [reconfig]: Registering account...
2017/07/16 19:14:31 [reconfig]: Registered!
2017/07/16 19:14:31 [reconfig]: Verifying my-domain.co.uk...
2017/07/16 19:14:31 [reconfig]: Traceback (most recent call last):
2017/07/16 19:14:31 [reconfig]:   File "/bin/acme_tiny", line 198, in <module>
2017/07/16 19:14:31 [reconfig]:     main(sys.argv[1:])
2017/07/16 19:14:31 [reconfig]:   File "/bin/acme_tiny", line 194, in main
2017/07/16 19:14:31 [reconfig]:     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
2017/07/16 19:14:31 [reconfig]:   File "/bin/acme_tiny", line 123, in get_crt
2017/07/16 19:14:31 [reconfig]:     wellknown_path, wellknown_url))
2017/07/16 19:14:31 [reconfig]: ValueError: Wrote file to /var/www/default/challenges/ACBm7r_OtUHsenWCp1AehdwLkHkz--22OYPBv9Qu4L0, but couldn't download http://my-domain.co.uk/.well-known/acme-challenge/ACBm7r_OtUHsenWCp1AehdwLkHkz--22OYPBv9Qu4L0
2017/07/16 19:14:31 [reconfig]: ================================================================================
2017/07/16 19:14:31 [reconfig]: Failed to sign my-domain.co.uk, is DNS set up properly?
2017/07/16 19:14:31 [reconfig]: ================================================================================
2017/07/16 19:14:31 [reconfig]: Failed to obtain certs for my-domain.co.uk
2017/07/16 19:14:31 Watching docker events
2017/07/16 19:14:32 Contents of /var/run/domains did not change. Skipping notification 'reconfig'
root@scw-6902c7:~#
```

**Comment by SteveLTN** [comment]
@wdmtech 
Hi!
You need to open port 80 and 443 of HTTPS-PORTAL, instead of opening the ports of your original app. PORTAL works as a reverse proxy :-)

**Comment by puneetjindal** [comment]
@wdmtech : I am using Azure Container Service. Ports are open but still the same error.

**Comment by SteveLTN** [comment]
@puneetjindal can you visit your app through 80, without https-portal?

**Comment by falcon8823** [comment]
I've faced same issue!

ACME Tiny trys to request the challenge path from inside the container.
https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py#L117

I verify to access mydomain from the container by ping.
And it seems OK.

```
$ ping mydomain.com
PING mydomain.com (x.x.x.x): 56 data bytes
64 bytes from x.x.x.x: icmp_seq=0 ttl=64 time=0.049 ms
64 bytes from x.x.x.x: icmp_seq=1 ttl=64 time=0.089 ms
64 bytes from x.x.x.x: icmp_seq=2 ttl=64 time=0.075 ms
64 bytes from x.x.x.x: icmp_seq=3 ttl=64 time=0.081 ms
^C--- mydomain.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.049/0.074/0.089/0.000 ms
```

But, python's urlopen seems not to work.
I got `No route to host` error.

```
$ python
>>> from urllib2 import urlopen
>>> urlopen('http://mydomain.com/.well-known/acme-challenge/....')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 113] No route to host>
```

I will check more deeply.

**Comment by falcon8823** [comment]
I found this issue might be a docker's problem.
For a workaround,  I disable userland-proxy of docker daemon.
